### ISSUE TITLE
Streaming from Open Broadcasting Software

### ISSUE THREAD

**Issue by abourget** [ossrs/httpx-static#52]
I've trying to stream from OBS (obsproject.com) to `go-oryx` but when I try with merely pointing to rtmp://localhost/live/feed I get this output log:

```
[oryx][trace] 2016/02/08 20:18:30 [30709][101] rtmp accept 192.168.86.168:49555
[oryx][trace] 2016/02/08 20:18:30 [30709][101] rollback to simple handshake.
[oryx][trace] 2016/02/08 20:18:30 [30709][101] input chunk size to 4096
[oryx][trace] 2016/02/08 20:18:30 [30709][101] connect at rtmp://192.168.86.151/live AMF0
[oryx][trace] 2016/02/08 20:18:30 [30709][101] output chunk size to 60000
[oryx][trace] 2016/02/08 20:18:30 [30709][101] client identified, type=fmle-publish, stream_name=feed, duration=0.00
[oryx][trace] 2016/02/08 20:18:30 [30709][101] redirect vhost 192.168.86.151 to __defaultVhost__
[oryx][trace] 2016/02/08 20:18:30 [30709][101] drop command message, name is @setDataFrame
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Audio
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Video
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Audio
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Video
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Audio
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Video
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Audio
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Video
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Audio
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Audio
[oryx][trace] 2016/02/08 20:18:31 [30709][101] drop unknown message, type is Video
...
```

with an on-going list of Audio and Video dropped messages.

Anything I can do to fix this ?

thanks for the software btw !

**Comment by winlinvip** [comment]
发现会有卡死的情况，用SIGUSR1让程序退出：

```
kill -s SIGUSR1 15782
```

日志如下：

```
[oryx][trace] 2016/02/22 11:43:18 [15782][100] got signal user defined signal 1
panic: panic by SIGUSR1/2

goroutine 31 [running]:
runtime.panic(0x682640, 0xc2080011c0)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/ossrs/go-oryx/app.(*Server).onSignal(0xc20802a000, 0x7f36e6e501d8, 0xa)
    /home/winlin/go/src/github.com/ossrs/go-oryx/app/server.go:282 +0x235
github.com/ossrs/go-oryx/app.func·011()
    /home/winlin/go/src/github.com/ossrs/go-oryx/app/server.go:332 +0x9e
created by github.com/ossrs/go-oryx/app.(*Server).Run
    /home/winlin/go/src/github.com/ossrs/go-oryx/app/server.go:334 +0x3d2

goroutine 16 [semacquire]:
sync.runtime_Semacquire(0xc2080001ac)
    /usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc20802a030)
    /usr/local/go/src/pkg/sync/waitgroup.go:129 +0x14b
github.com/ossrs/go-oryx/app.(*Server).Run(0xc20802a000, 0x0, 0x0)
    /home/winlin/go/src/github.com/ossrs/go-oryx/app/server.go:337 +0x3f5
main.serve(0xc20802a000, 0x7f36e6e54688, 0x64, 0x0)
    /home/winlin/git/go-oryx/oryx.go:59 +0x591
main.run(0xc20802a000, 0x7f36e6e54688, 0x64, 0x0)
    /home/winlin/git/go-oryx/oryx_unix.go:51 +0x359
main.func·001(0x0)
    /home/winlin/git/go-oryx/oryx.go:90 +0x2ab
main.main()
    /home/winlin/git/go-oryx/oryx.go:91 +0x532

goroutine 19 [finalizer wait]:
runtime.park(0x415260, 0x92daf0, 0x92bd49)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x92daf0, 0x92bd49)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
    /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
    /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [sleep]:
time.Sleep(0xb2d05e00)
    /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
github.com/ossrs/go-oryx/app.func·008()
    /home/winlin/go/src/github.com/ossrs/go-oryx/app/server.go:219 +0x403
created by github.com/ossrs/go-oryx/app.(*Server).initializeRuntime
    /home/winlin/go/src/github.com/ossrs/go-oryx/app/server.go:222 +0x114

goroutine 28 [semacquire]:
sync.runtime_Semacquire(0xc2080284ac)
    /usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*Mutex).Lock(0xc2080284a8)
    /usr/local/go/src/pkg/sync/mutex.go:66 +0xd6
github.com/ossrs/go-oryx/protocol.func·013()
    /home/winlin/go/src/github.com/ossrs/go-oryx/protocol/rtmp.go:1495 +0x4a
github.com/ossrs/go-oryx/protocol.(*RtmpConnection).flush(0xc208028410, 0x0, 0x0)
    /home/winlin/go/src/github.com/ossrs/go-oryx/protocol/rtmp.go:1500 +0x381
github.com/ossrs/go-oryx/protocol.(*RtmpConnection).write(0xc208028410, 0x7f36e6e56580, 0xc20809e74c, 0xc200000000, 0x0, 0x0)
    /home/winlin/go/src/github.com/ossrs/go-oryx/protocol/rtmp.go:1690 +0xb9
github.com/ossrs/go-oryx/protocol.(*RtmpConnection).SetWindowAckSize(0xc208028410, 0x7f36002625a0, 0x0, 0x0)
    /home/winlin/go/src/github.com/ossrs/go-oryx/protocol/rtmp.go:1109 +0xeb
github.com/ossrs/go-oryx/agent.(*Rtmp).cycle(0xc2080502c0, 0xc208028410, 0x0, 0x0)
    /home/winlin/go/src/github.com/ossrs/go-oryx/agent/rtmp.go:188 +0x694
github.com/ossrs/go-oryx/agent.func·005(0x7f36e6e54838, 0xc20802a000)
    /home/winlin/go/src/github.com/ossrs/go-oryx/agent/rtmp.go:153 +0x527
github.com/ossrs/go-oryx/app.func·013()
    /home/winlin/go/src/github.com/ossrs/go-oryx/app/server.go:382 +0x113
created by github.com/ossrs/go-oryx/app.(*Server).GFork
    /home/winlin/go/src/github.com/ossrs/go-oryx/app/server.go:387 +0x115
[winlin@SRS go-oryx]$ 
```

**Comment by winlinvip** [comment]
goroutine 16在等28退出，导致挂起。
